defaults:
  - _self_
# Used if running do=evaluate
  - scenarios: 
    - hyggeswag
    - dane
    - da-gym-2000
    - nordjylland-news
    - hashtag-twitterhjerne
    - citizenship-test
    - da-cloze-self-test
    - angry-tweets
  - model: test
# Used if running do=databuild
  - databuild: prompt_answer
# Used if running do=train
  - train: default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

do: ???

outputs: job-outputs

evaluation: 
  local_results: "local-computations/result-db"
  debug: false
  do_not_score_before: "2023-09-28-23-00"
  rescore: false
  seed: 1887
  robustness_augment: false
  fairness_augment: false
  skip_unaugmented: false
  api_call_cache: "local-computations/api-cache"

model:
  batch_size:  32

download_no_cache: false

model_paths:
  fasttext: "local-models/lid.176.bin"
  dsl3gram: "local-models/dsl_3gram.klm"

wandb:
  enabled: true
  entity: "sorenmulli"
  project: "nlgenda"
  artifact_cache: "local-computations/wandb-cache.json"
  cache_update: false

hydra:
  run:
    dir: ${outputs}/${hydra.job.name}
  sweep:
    dir: ${outputs}/${hydra.job.name}
    subdir: ${hydra.job.num}
  job:
    name: ${job_base_name}-${now:%Y%m%d-%H%M%S}
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${job_base_name}.log

job_base_name: job
