angry_tweets:
  name: "Angry Tweets"
  path: "sorenmulli/angry-tweets-mini"
  pre_prompt: "Vurdér, om sentimentet i følgende tweet er 'positiv', 'neutral' eller 'negativ'. Svar kun med et enkelt ord.\n# TWEET\n"
  post_prompt: "\n# SENTIMENT:\nSentimentet var "
  dataset_split: "validation"
  task:
    type: "angry-tweets"
    all_labels: ["negative", "neutral", "positive"]
    id_features: []
