[tool.pylint]
disable = "missing-module-docstring, missing-function-docstring, missing-class-docstring, too-few-public-methods, inconsistent-return-statements"
notes="FIXME,XXX"
good-names="df,i,j,k"
extension-pkg-allow-list="kenlm"
generated-members="torch.*"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100


[[tool.mypy.overrides]]
module = [
    "datasets",
    "fasttext",
    "kenlm",
    "transformers",
    "huggingface_hub",
    "huggingface_hub.file_download",
    "transformers.modeling_utils",
]
ignore_missing_imports = true
