citizenship_test:
  name: "Citizenship Test"
  path: "sorenmulli/citizenship-test-da"
  pre_prompt: "Svar helt kort på spørgsmålet.\n# SPØRGSMÅL\n"
  post_prompt: "\n# SVAR\nSvaret er\n"
  type: "free-generation"
  task:
    prompt_feature: "question"
    id_features: ["origin", "index"]
    type: "default-mc-letter-options"
