citizenship_test:
  name: "Citizenship Test"
  path: "sorenmulli/citizenship-test-da"
  task:
    prompt_feature: "question"
    id_features: ["origin", "index"]
    type: "default-mc-letter-options"
