da_gym_2000:
  name: "Da. Gym 2000"
  path: "sorenmulli/da-gym-2000"
  pre_prompt: "\"{context}\"\n\n"
  post_prompt: " "
  task:
    type: "default-mc-letter-context"
    prompt_feature: "question"
    id_features: ["task_title", "index"]
