hyggeswag:
  name: "HyggeSwag"
  path: "sorenmulli/hyggeswag"
  pre_prompt: "Fuldend sætningen. Skriv intet andet end sætningens korte fortsættelse.\n"
  task:
    prompt_feature: "ctx"
    id_features: ["source_id", "ind"]
    type: "default-mc"
