nordjylland_news:
  name: "Nordjylland News"
  path: "sorenmulli/nordjylland-news-summarization-subset"
  pre_prompt: "Skriv et dansk resumé på én sætning af følgende tekst.\n# TEKST\n"
  post_prompt: "\n# RESUMÉ\n"
  task:
    type: "default-answer-similarity"
    prompt_feature: "text"
    answer_feature: "summary"
    id_features: ["ind"]
