defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

do: ???
seed: 42

outputs: job-outputs

prompt_answer_da:
  push_to_hub: true
  hub_private: true
  target: "sorenmulli/prompt-answer-da"

citizenship_test_da:
  scrape: true
  clean: true
  push_to_hub: true
  hub_private: false
  target: "sorenmulli/citizenship-test-da"
  calc_lm: true
  scored_tofix: "local-computations/scores-to-fix.csv"
  verified_tofix: "local-computations/verified-to-fix.csv"

hyggeswag:
  push_to_hub: true
  hub_private: true
  target: "sorenmulli/hyggeswag"
  translation:
    todo_file: "local-computations/hellaswag-to-translate.csv"
    done_file: "local-computations/hellaswag-translated.csv"


model_paths:
  fasttext: "local-models/lid.176.bin"
  dsl3gram: "local-models/dsl_3gram.klm"

hydra:
  run:
    dir: ${outputs}/${hydra.job.name}-${now:%Y%m%d-%H%M%S}
  job:
    name: nlgenda
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
