defaults:
  - _self_
# Used if running do=evaluate
  - scenario: hyggeswag
  - model: test
# Used if running do=databuild
  - databuild: prompt_answer
# Used if running do=train
  - train: default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

do: ???

outputs: job-outputs

evaluation: 
  local_results: "local-computations/result-db"
  debug: false

download_no_cache: false

model_paths:
  fasttext: "local-models/lid.176.bin"
  dsl3gram: "local-models/dsl_3gram.klm"

wandb:
  enabled: true
  entity: "sorenmulli"
  project: "nlgenda"

hydra:
  run:
    dir: ${outputs}/${hydra.job.name}
  sweep:
    dir: ${outputs}/${hydra.job.name}
    subdir: ${hydra.job.num}
  job:
    name: ${job_base_name}-${now:%Y%m%d-%H%M%S}
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${job_base_name}.log

job_base_name: nlgenda
