defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

do: ???
seed: 42

outputs: job-outputs

prompt_answer_da:
  push_to_hub: true
  hub_private: false
  target: "sorenmulli/prompt-answer-da"

model_paths:
  fasttext: "local-models/lid.176.bin"

hydra:
  run:
    dir: ${outputs}/${hydra.job.name}-${now:%Y%m%d-%H%M%S}
  job:
    name: nlgenda
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
