defaults:
  - _self_
# Used if running do=evaluate
  - scenario: hyggeswag
  - model: test
# Used if running do=databuild
  - databuild: prompt_answer

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

do: ???

outputs: job-outputs

evaluation: 
  local_results: "local-computations/result-db"
  debug: false

model_paths:
  fasttext: "local-models/lid.176.bin"
  dsl3gram: "local-models/dsl_3gram.klm"

wandb:
  enabled: true
  entity: "sorenmulli"
  project: "nlgenda-benchmarking"

hydra:
  run:
    dir: ${outputs}/${hydra.job.name}-${now:%Y%m%d-%H%M%S}
  sweep:
    dir: ${outputs}/${hydra.job.name}-${now:%Y%m%d-%H%M%S}
    subdir: ${hydra.job.num}
  job:
    name: nlgenda
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
