base_model: "meta-llama/Llama-2-7b-hf"

steps: 10_000
warmup_steps: 100
resume: false

optimizer: "adamw_torch"
lr: 5e-5
scheduler: "cosine_with_restarts"
weight_decay: 0.01

batch_size: 4
accumulation: 4
eval_batch_size: 8
eval_accumulation: 1

fp16: true

eval: true
eval_every: 100
save_every: 100
save_limit: 5
log_every: 10

lora:
  enabled: true
  r: 8
  alpha: 32
  dropout: 0.1
  target_modules: ["q_proj", "v_proj"]

data:
  datasets: ["uonlp/CulturaX:da", "DDSC/dagw_reddit_filtered_v1.0.0"]
  seed: 1887
  text_col: "text"
  test_examples: 10000
  validation_examples: 100
  context_tokens: 1024
  workers: 0

debug: false
